src/Entity/Zero.php
<?php

/*
 * Copyright (C) 2019 Mazarini <mazarini@protonmail.com>.
 * This file is part of mazarini/crud-bundle.
 *
 * mazarini/crud-bundle is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * mazarini/crud-bundle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Mazarini\ToolsBundle\Entity\EntityInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ZeroRepository")
 */
class Zero implements EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id = 0;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $Col3 = '';

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $Col4 = '';

    public function isNew(): bool
    {
        return 0 === $this->id;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getCol3(): string
    {
        return $this->Col3;
    }

    public function setCol3(string $Col3): self
    {
        $this->Col3 = $Col3;

        return $this;
    }

    public function getCol4(): string
    {
        return $this->Col4;
    }

    public function setCol4(string $Col4): self
    {
        $this->Col4 = $Col4;

        return $this;
    }
}

templates/pagination/_list.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	<table class="table">
		<thead>
			<tr>
				{% block page_title %}
					<th>Id</th>
					<th>Col3</th>
					<th>Col4</th>
					<th>actions</th>
				{% endblock page_title %}
			</tr>
		</thead>
		<tbody>
			{% for entity in data.entities %}
				<tr>
					{% block page_row %}
						<td>{{ entity.id }}</td>
						<td>{{ entity.col3 }}</td>
						<td>{{ entity.col4 }}</td>
					{% endblock page_row %}
					{% block page_button %}
						<td>
							{% if data.links['show-' ~ entity.id].url != '#' %}
								<a class="btn btn-primary btn-sm" href="{{ data.links['show-' ~ entity.id].url }}" role=" button">Show</a>
							{% endif %}
							{% if data.links['edit-' ~ entity.id].url != '#' %}
								<a class="btn btn-primary btn-sm" href="{{ data.links['edit-' ~ entity.id].url }}" role=" button">Edit</a>
							{% endif %}
						</td>
					{% endblock page_button %}
				</tr>
			{% else %}
				<tr>
					{% block page_not_found %}
						<td colspan="4">no records found</td>
					{% endblock page_not_found %}
				</tr>

			{% endfor %}
		</tbody>
		<thead>
			{% if data.links['new'].url != '#' %}
				{% block page_new %}{% endblock page_new %}
			{% endif %}
		</thead>
	</table>
	{% embed 'pagination/nav.html.twig' %}{% endembed %}
{% endblock content %}

templates/pagination/first.html.twig
{# lib/Resources/views/pagination/first.html.twig #}

{% extends 'pagination/item.html.twig' %}

{% block label %}
	First
{% endblock label %}

templates/pagination/last.html.twig
{# lib/Resources/views/pagination/last.html.twig #}

{% extends 'pagination/item.html.twig' %}

{% block label %}
	Last
{% endblock label %}

templates/pagination/nav.html.twig
{# lib/Resources/views/pagination/nav.html.twig #}

{% block pagination_container %}
	{% if data.pagination.lastPage > 0 %}
		<nav>
			<ul class="pagination justify-content-center">
				{% if data.pagination.lastPage > 5 %}
					{% include 'pagination/first.html.twig' with {'link': data.links.first} only %}
					{% include 'pagination/prev.html.twig' with {'link': data.links.previous} only %}
					{% set start_n = data.pagination.currentPage %}
					{% set end_n = data.pagination.currentPage %}
				{% else %}
					{% set start_n = 1 %}
					{% set end_n = data.pagination.lastPage %}
				{% endif %}
				{% for number in start_n..end_n %}
					{% if data.pagination.currentPage == number %}
						{% include 'pagination/item.html.twig' with {'link': data.links['page-' ~ number], number: number} only %}
					{% else %}
						{% block number %}
							{% include 'pagination/item.html.twig' with {'link': data.links['page-' ~ number], number: number} only %}
						{% endblock number %}
					{% endif %}
				{% endfor %}
				{% if data.pagination.lastPage > 5 %}
					{% include 'pagination/next.html.twig' with {'link': data.links.next} only %}
					{% include 'pagination/last.html.twig' with {'link': data.links.last} only %}
				{% endif %}
			</ul>
		</nav>
	{% endif %}
{% endblock pagination_container %}

templates/pagination/next.html.twig
{# lib/Resources/views/pagination/next.html.twig #}

{% extends 'pagination/item.html.twig' %}

{% block label %}
	Next
{% endblock label %}

templates/pagination/number.html.twig
{# lib/Resources/views/pagination/number.html.twig #}

{% block pagination_container %}
	{% if data.pagination.lastPage > 0 %}
		<nav>
			<ul class="pagination justify-content-center">
				{% for number in 1..data.pagination.lastPage %}
					{% if data.pagination.currentPage == number %}
						{% include 'pagination/item.html.twig' with {'link': data.links['page_' ~ number], 'number': number} only %}
					{% else %}
						{% block number %}
							{% include 'pagination/item.html.twig' with {'link': data.links['page_' ~ number], 'number': number} only %}
						{% endblock number %}
					{% endif %}
				{% endfor %}
			</ul>
		</nav>
	{% endif %}
{% endblock pagination_container %}

templates/pagination/prev.html.twig
{# lib/Resources/views/pagination/prev.html.twig #}

{% extends 'pagination/item.html.twig' %}

{% block label %}
	Prev
{% endblock label %}